/**
 * Renders a Skill run's working-notes channel (markdown-ish text:
 * headings, bullets, numbered lists, bold/italic/code) into a formatted
 * .docx, returned as base64 for the task pane to open via Office.js
 * Application.createDocument. Pure JS (docx package) -- no native deps,
 * runs on Render as-is.
 *
 * Deliberately modest: covers the structures Skills actually emit in
 * their Output Packages. Tables and images are out of scope; unknown
 * markdown falls through as plain paragraphs, so nothing is dropped.
 */

const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } = require("docx");

const NUMBERING_REF = "working-notes-numbered";

/** `**bold**`, `*italic*`, and `code` spans -> styled TextRuns. */
function parseInlineRuns(text) {
  const runs = [];
  const tokenRe = /(\*\*[^*]+\*\*|\*[^*]+\*|`[^`]+`)/g;
  let last = 0;
  let match;
  while ((match = tokenRe.exec(text))) {
    if (match.index > last) {
      runs.push(new TextRun(text.slice(last, match.index)));
    }
    const token = match[0];
    if (token.startsWith("**")) {
      runs.push(new TextRun({ text: token.slice(2, -2), bold: true }));
    } else if (token.startsWith("`")) {
      runs.push(new TextRun({ text: token.slice(1, -1), font: "Consolas" }));
    } else {
      runs.push(new TextRun({ text: token.slice(1, -1), italics: true }));
    }
    last = match.index + token.length;
  }
  if (last < text.length) {
    runs.push(new TextRun(text.slice(last)));
  }
  return runs.length > 0 ? runs : [new TextRun("")];
}

const HEADING_LEVELS = [HeadingLevel.HEADING_1, HeadingLevel.HEADING_2, HeadingLevel.HEADING_3];

function markdownToParagraphs(markdown) {
  const paragraphs = [];
  let buffer = [];
  // Each contiguous numbered list gets its own numbering instance so
  // numbering restarts at 1 instead of continuing across lists.
  let listInstance = 0;
  let inNumberedList = false;

  const flushBuffer = () => {
    if (buffer.length === 0) return;
    paragraphs.push(new Paragraph({ children: parseInlineRuns(buffer.join(" ")), spacing: { after: 120 } }));
    buffer = [];
  };

  for (const rawLine of markdown.split("\n")) {
    const line = rawLine.trimEnd();

    const headingMatch = line.match(/^(#{1,6})\s+(.*)$/);
    const bulletMatch = line.match(/^\s*[-*]\s+(.*)$/);
    const numberedMatch = line.match(/^\s*\d+[.)]\s+(.*)$/);

    if (!numberedMatch && line.trim() !== "") {
      inNumberedList = false;
    }

    if (headingMatch) {
      flushBuffer();
      const level = Math.min(headingMatch[1].length, HEADING_LEVELS.length) - 1;
      paragraphs.push(
        new Paragraph({
          heading: HEADING_LEVELS[level],
          children: parseInlineRuns(headingMatch[2].trim()),
          spacing: { before: 240, after: 120 },
        })
      );
    } else if (bulletMatch) {
      flushBuffer();
      paragraphs.push(
        new Paragraph({ children: parseInlineRuns(bulletMatch[1]), bullet: { level: 0 }, spacing: { after: 60 } })
      );
    } else if (numberedMatch) {
      flushBuffer();
      if (!inNumberedList) {
        listInstance++;
        inNumberedList = true;
      }
      paragraphs.push(
        new Paragraph({
          children: parseInlineRuns(numberedMatch[1]),
          numbering: { reference: NUMBERING_REF, level: 0, instance: listInstance },
          spacing: { after: 60 },
        })
      );
    } else if (/^\s*(-{3,}|_{3,}|\*{3,})\s*$/.test(line)) {
      flushBuffer(); // horizontal rule -- treat as a paragraph break
    } else if (line.trim() === "") {
      flushBuffer();
    } else {
      buffer.push(line.trim());
    }
  }
  flushBuffer();

  return paragraphs;
}

async function buildWorkingNotesDocx({ skillDisplayName, matterId, notesMarkdown }) {
  const generatedAt = new Date().toLocaleString("en-GB", { dateStyle: "medium", timeStyle: "short" });

  const children = [
    new Paragraph({
      heading: HeadingLevel.TITLE,
      children: [new TextRun(`${skillDisplayName} — Working Notes`)],
      spacing: { after: 120 },
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: `Matter: ${matterId || "(no matter resolved)"}  ·  Generated by Suade, ${generatedAt}`,
          italics: true,
          color: "5B6470",
        }),
      ],
      spacing: { after: 240 },
    }),
    ...markdownToParagraphs(notesMarkdown),
  ];

  const doc = new Document({
    numbering: {
      config: [
        {
          reference: NUMBERING_REF,
          levels: [
            {
              level: 0,
              format: "decimal",
              text: "%1.",
              alignment: AlignmentType.START,
              style: { paragraph: { indent: { left: 720, hanging: 360 } } },
            },
          ],
        },
      ],
    },
    sections: [{ children }],
  });

  return Packer.toBase64String(doc);
}

module.exports = { buildWorkingNotesDocx };
